<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b816fe0b-2e8f-4220-979c-570a2f1d802f</testSuiteGuid>
   <testCaseLink>
      <guid>e98528cd-04df-4125-af69-d38e01c92903</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC001</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a60e51b-d2f0-4fce-b2f7-6e4545dba031</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>41774a84-3c71-4477-bf38-55c13d80dd11</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC002-TaoBienPASSWORD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c110bdb-2e88-48f1-ae27-b7fd95d4d805</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f7a7b8b8-6a89-40ef-81eb-dded0c1ee186</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC003</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be63253f-9a37-45fa-ae88-56b8b6853930</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b79d1bac-aced-47e5-840a-47f28204b005</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC004</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1944b79-d177-48e2-a20b-ddf1db220bd9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f2fd5118-403c-47a6-87df-1b23d2f6758f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC005</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec506b3b-7ff3-4730-bf7f-a41bda2a96d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49596ae9-b29f-4256-98f0-1994a2f23367</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
