<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Vetify - Wait - Đặt biến</description>
   <name>TS_Lab2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8c178485-a3c7-4d9d-9c8b-fa5056462e4b</testSuiteGuid>
   <testCaseLink>
      <guid>f0c4d224-fef2-4791-bd57-28abeb3c228a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC001</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a60e51b-d2f0-4fce-b2f7-6e4545dba031</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9691236-4828-4330-8c4f-5edb30d7f935</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC002-TaoBienPASSWORD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c110bdb-2e88-48f1-ae27-b7fd95d4d805</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a7705b22-ef82-4e82-9cfa-1b3888b068d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC003</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be63253f-9a37-45fa-ae88-56b8b6853930</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>955d4d6e-468d-4b09-9c99-7a5577e7cb5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC004</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1944b79-d177-48e2-a20b-ddf1db220bd9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>449df4cc-1a95-4e35-bb5f-c8db2962804c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC005</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec506b3b-7ff3-4730-bf7f-a41bda2a96d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49596ae9-b29f-4256-98f0-1994a2f23367</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2ebffabf-abb4-49e8-9e71-c0ffaa8afade</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC006</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0f0e6e1-2bd0-4033-8bed-897b226f73cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec463c37-9c1d-4106-be86-a55119026250</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
